DROP INDEX APPS.XXINTG_IPM_PEDIGREE_N1;

CREATE INDEX APPS.XXINTG_IPM_PEDIGREE_N1 ON XXINTG.XXINTG_IPM_PEDIGREE
(DELIVERY_DETAIL_ID)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
