DROP PACKAGE APPS.XX_INTG_BUSINESS_EVENT_PKG;

CREATE OR REPLACE PACKAGE APPS."XX_INTG_BUSINESS_EVENT_PKG" 
AS

FUNCTION XX_INTG_BEVENT_GXP  ( p_subscription_guid IN RAW,p_event IN OUT NOCOPY wf_event_t) RETURN VARCHAR2;

END;
/
