DROP PACKAGE APPS.XXINTG_APPROVAL_GROUP_PKG;

CREATE OR REPLACE PACKAGE APPS."XXINTG_APPROVAL_GROUP_PKG" 
IS
   PROCEDURE XXINTG_APPROVAL_GROUP_PRO(p_errbuf OUT VARCHAR2, P_RETCODE OUT VARCHAR2);   
END; 
/
