DROP TABLE APPS.XX_AR_RTN_RSV_GBLTMP_TBL CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE APPS.XX_AR_RTN_RSV_GBLTMP_TBL
(
  CM_NUM                 NUMBER,
  CM_DATE                DATE,
  CUST_NUM               VARCHAR2(30 BYTE),
  CUST_NAME              VARCHAR2(240 BYTE),
  RET_REASON             VARCHAR2(240 BYTE),
  RET_PO_NUM             VARCHAR2(240 BYTE),
  RET_ORD_NUM            VARCHAR2(100 BYTE),
  RET_ORD_TYPE           VARCHAR2(100 BYTE),
  CREDITED_ITEM          VARCHAR2(100 BYTE),
  CREDITED_ITEM_DESC     VARCHAR2(240 BYTE),
  CINV_AMT_FUNC          NUMBER,
  CINV_EXCHG_RATE        NUMBER,
  DIVISIONALIZATION      VARCHAR2(240 BYTE),
  CREDIT_LINE_AMT        NUMBER,
  CREDIT_LINE_TYPE       VARCHAR2(100 BYTE),
  CREDIT_INV_AMT         NUMBER,
  INV_CUR                VARCHAR2(100 BYTE),
  RET_REV_ACCT           VARCHAR2(100 BYTE),
  ORIG_INV_NUM           VARCHAR2(100 BYTE),
  ORIG_ORDER_NUM         VARCHAR2(100 BYTE),
  ORIG_INV_DATE          DATE,
  ORIG_PO_NUM            VARCHAR2(240 BYTE),
  ORIG_INV_AMOUNT        NUMBER,
  PREV_CUST_TRX_ID       NUMBER,
  INTF_LINE_ATTR1        VARCHAR2(240 BYTE),
  INTF_LINE_ATTR6        VARCHAR2(240 BYTE),
  ORIG_LINE_ID           VARCHAR2(240 BYTE),
  ORIG_CUST_TRX_ID       VARCHAR2(240 BYTE),
  ORIG_CUST_TRX_LINE_ID  VARCHAR2(240 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE;


CREATE INDEX APPS.XX_AR_RTN_RSV_GBLTMP_N1 ON APPS.XX_AR_RTN_RSV_GBLTMP_TBL
(ORIG_LINE_ID, ORIG_ORDER_NUM);

CREATE INDEX APPS.XX_AR_RTN_RSV_GBLTMP_N2 ON APPS.XX_AR_RTN_RSV_GBLTMP_TBL
(INTF_LINE_ATTR1, INTF_LINE_ATTR6);

CREATE INDEX APPS.XX_AR_RTN_RSV_GBLTMP_N3 ON APPS.XX_AR_RTN_RSV_GBLTMP_TBL
(ORIG_CUST_TRX_ID, ORIG_CUST_TRX_LINE_ID);
