DROP TABLE APPS.XX_AUS_ASL_UPDATES CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_AUS_ASL_UPDATES
(
  ITEM                       VARCHAR2(400 BYTE),
  CURRENT_FG_SOURCE_SITE     VARCHAR2(400 BYTE),
  NEW_CAT_ORG_SOURCING_RULE  VARCHAR2(30 BYTE),
  NEW_CAT_ORG_SOURCE         VARCHAR2(30 BYTE),
  NEW_ASL_SUPPLIER           VARCHAR2(4000 BYTE),
  NEW_FG_SOURCE_SITE         VARCHAR2(4000 BYTE),
  PROPOSED_ACTION            VARCHAR2(4000 BYTE),
  ACCOUNTABLE_TO             VARCHAR2(4000 BYTE),
  SR_ASSIGNMENT_ID           NUMBER
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
