DROP TABLE APPS.XX_CA_NEWDEAL_ASL_PRICES CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_CA_NEWDEAL_ASL_PRICES
(
  ITEM_NUMBER             VARCHAR2(100 BYTE),
  VENDOR_NAME             VARCHAR2(1000 BYTE),
  VENDOR_ITEM             VARCHAR2(100 BYTE),
  PRICE                   NUMBER,
  VENDOR_ID               NUMBER,
  VENDOR_SITE_ID          NUMBER,
  INVENTORY_ITEM_ID       NUMBER,
  UOM                     VARCHAR2(10 BYTE),
  LINE_ORIG_REF           VARCHAR2(100 BYTE),
  USING_ORGANIZATION_ID   NUMBER,
  OWNING_ORGANIZATION_ID  NUMBER,
  PO_HEADER_ID            NUMBER,
  PO_LINE_ID              NUMBER,
  ERROR_MESSAGE           VARCHAR2(4000 BYTE),
  ASL_ID                  NUMBER,
  CURRENCY                VARCHAR2(10 BYTE),
  SOURCING_SITE_CATEGORY  NUMBER,
  SOURCING_SITE_CAT_NAME  VARCHAR2(30 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
