DROP TABLE APPS.XX_CONSGN_RESERVE_TBL CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_CONSGN_RESERVE_TBL
(
  ORG                 VARCHAR2(3 BYTE),
  ITEM                VARCHAR2(50 BYTE),
  DEMAND_TYPE         VARCHAR2(25 BYTE),
  ORDER_NUMBER        VARCHAR2(25 BYTE),
  LINE_NUMBER         NUMBER,
  QUANTITY            NUMBER,
  SUPPLY_TYPE         VARCHAR2(25 BYTE),
  SUPPLY_SOURCE_NAME  VARCHAR2(200 BYTE),
  LOT                 VARCHAR2(25 BYTE),
  SUB                 VARCHAR2(25 BYTE),
  LOC                 VARCHAR2(50 BYTE),
  LPN                 VARCHAR2(25 BYTE),
  FLAG                VARCHAR2(25 BYTE),
  ATTRIBUTE1          VARCHAR2(2000 BYTE),
  ATTRIBUTE2          VARCHAR2(2000 BYTE),
  ATTRIBUTE3          VARCHAR2(25 BYTE),
  ATTRIBUTE4          VARCHAR2(25 BYTE),
  ATTRIBUTE5          VARCHAR2(25 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
