DROP TABLE APPS.XX_DEACTIVE_ROLE CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_DEACTIVE_ROLE
(
  USER_NAME     VARCHAR2(320 BYTE),
  ROLE_NAME     VARCHAR2(320 BYTE),
  DISPLAY_NAME  VARCHAR2(360 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
