DROP TABLE APPS.XX_DBA_EXISTING_HELD_PRGS CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_DBA_EXISTING_HELD_PRGS
(
  MAINTENANCE_DATE  DATE,
  HOLD_FLAG         VARCHAR2(1 BYTE)            NOT NULL,
  REQUEST_ID        NUMBER(15)                  NOT NULL,
  LAST_UPDATE_DATE  DATE                        NOT NULL,
  LAST_UPDATED_BY   NUMBER(15)                  NOT NULL,
  STATUS_CODE       VARCHAR2(1 BYTE)            NOT NULL,
  PHASE_CODE        VARCHAR2(1 BYTE)            NOT NULL
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
