DROP TABLE APPS.XX_DEBUG CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_DEBUG
(
  MODULE   VARCHAR2(100 BYTE),
  MESSAGE  VARCHAR2(1000 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


GRANT SELECT ON APPS.XX_DEBUG TO INTG_XX_NONHR_RO;

GRANT SELECT ON APPS.XX_DEBUG TO XXAPPSREAD;
