DROP TABLE APPS.XX_EMF_DEBUG_TRACE_Q CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_EMF_DEBUG_TRACE_Q
(
  SESSION_ID         NUMBER,
  DEBUG_ID           NUMBER,
  DEBUG_LEVEL        VARCHAR2(100 BYTE),
  DEBUG_TEXT         VARCHAR2(4000 BYTE),
  REQUEST_ID         NUMBER,
  PROCESS_ID         NUMBER,
  PROCESS_NAME       VARCHAR2(100 BYTE),
  CREATED_BY_USER    VARCHAR2(240 BYTE),
  CREATED_BY         NUMBER,
  CREATION_DATE      DATE,
  LAST_UPDATED_BY    NUMBER,
  LAST_UPDATE_DATE   DATE,
  LAST_UPDATE_LOGIN  NUMBER,
  ATTRIBUTE1         VARCHAR2(240 BYTE),
  ATTRIBUTE2         VARCHAR2(240 BYTE),
  ATTRIBUTE3         VARCHAR2(240 BYTE),
  ATTRIBUTE4         VARCHAR2(240 BYTE),
  ATTRIBUTE5         VARCHAR2(240 BYTE),
  ATTRIBUTE6         VARCHAR2(240 BYTE),
  ATTRIBUTE7         VARCHAR2(240 BYTE),
  ATTRIBUTE8         VARCHAR2(240 BYTE),
  ATTRIBUTE9         VARCHAR2(240 BYTE),
  ATTRIBUTE10        VARCHAR2(240 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


GRANT SELECT ON APPS.XX_EMF_DEBUG_TRACE_Q TO XXAPPSREAD;
