DROP TABLE APPS.XX_EMF_PROCESS_PARAMETERS_BKUP CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_EMF_PROCESS_PARAMETERS_BKUP
(
  PROCESS_ID         NUMBER,
  PARAMETER_ID       NUMBER,
  PARAM_SEQ          NUMBER,
  PARAMETER_NAME     VARCHAR2(30 BYTE),
  PARAMETER_VALUE    VARCHAR2(60 BYTE),
  ENABLED_FLAG       VARCHAR2(1 BYTE),
  ORG_ID             NUMBER,
  CREATED_BY         NUMBER,
  CREATION_DATE      DATE,
  LAST_UPDATE_DATE   DATE,
  LAST_UPDATED_BY    NUMBER,
  LAST_UPDATE_LOGIN  NUMBER
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
