DROP TABLE APPS.XX_EMF_PROCESS_SETUP_BKUP CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_EMF_PROCESS_SETUP_BKUP
(
  PROCESS_ID            NUMBER,
  PROCESS_NAME          VARCHAR2(100 BYTE),
  DESCRIPTION           VARCHAR2(100 BYTE),
  PROCESS_TYPE          VARCHAR2(30 BYTE),
  OBJECT_TYPE           VARCHAR2(30 BYTE),
  MODULE_NAME           VARCHAR2(30 BYTE),
  NOTIFICATION_GROUP    VARCHAR2(150 BYTE),
  RUN_FREQUENCY         VARCHAR2(150 BYTE),
  RUNTIME               VARCHAR2(150 BYTE),
  ENABLED_FLAG          VARCHAR2(1 BYTE),
  DEBUG_LEVEL           NUMBER,
  DEBUG_TYPE            VARCHAR2(50 BYTE),
  PURGE_INTERVAL        NUMBER,
  PRE_VALIDATION_FLAG   VARCHAR2(1 BYTE),
  POST_VALIDATION_FLAG  VARCHAR2(1 BYTE),
  ERROR_TAB_IND         VARCHAR2(1 BYTE),
  ERROR_LOG_IND         VARCHAR2(10 BYTE),
  ORG_ID                NUMBER,
  ATTRIBUTE_CATEGORY    VARCHAR2(30 BYTE),
  ATTRIBUTE1            VARCHAR2(150 BYTE),
  ATTRIBUTE2            VARCHAR2(150 BYTE),
  ATTRIBUTE3            VARCHAR2(150 BYTE),
  ATTRIBUTE4            VARCHAR2(150 BYTE),
  ATTRIBUTE5            VARCHAR2(150 BYTE),
  ATTRIBUTE6            VARCHAR2(150 BYTE),
  ATTRIBUTE7            VARCHAR2(150 BYTE),
  ATTRIBUTE8            VARCHAR2(150 BYTE),
  ATTRIBUTE9            VARCHAR2(150 BYTE),
  ATTRIBUTE10           VARCHAR2(150 BYTE),
  ATTRIBUTE11           VARCHAR2(150 BYTE),
  ATTRIBUTE12           VARCHAR2(150 BYTE),
  ATTRIBUTE13           VARCHAR2(150 BYTE),
  ATTRIBUTE14           VARCHAR2(150 BYTE),
  ATTRIBUTE15           VARCHAR2(150 BYTE),
  ATTRIBUTE16           VARCHAR2(150 BYTE),
  ATTRIBUTE17           VARCHAR2(150 BYTE),
  ATTRIBUTE18           VARCHAR2(150 BYTE),
  ATTRIBUTE19           VARCHAR2(150 BYTE),
  ATTRIBUTE20           VARCHAR2(150 BYTE),
  ATTRIBUTE21           VARCHAR2(150 BYTE),
  ATTRIBUTE22           VARCHAR2(150 BYTE),
  ATTRIBUTE23           VARCHAR2(150 BYTE),
  ATTRIBUTE24           VARCHAR2(150 BYTE),
  ATTRIBUTE25           VARCHAR2(150 BYTE),
  ATTRIBUTE26           VARCHAR2(150 BYTE),
  ATTRIBUTE27           VARCHAR2(150 BYTE),
  ATTRIBUTE28           VARCHAR2(150 BYTE),
  ATTRIBUTE29           VARCHAR2(150 BYTE),
  ATTRIBUTE30           VARCHAR2(150 BYTE),
  CREATED_BY            NUMBER,
  CREATION_DATE         DATE,
  LAST_UPDATE_DATE      DATE,
  LAST_UPDATED_BY       NUMBER,
  LAST_UPDATE_LOGIN     NUMBER
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
