DROP TABLE APPS.XX_FND_ROLES CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_FND_ROLES
(
  USER_NAME  VARCHAR2(320 BYTE),
  ROLE_NAME  VARCHAR2(320 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


GRANT SELECT ON APPS.XX_FND_ROLES TO INTG_XX_NONHR_RO;
