DROP TABLE APPS.XX_FND_NEW_USER_LOAD CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_FND_NEW_USER_LOAD
(
  EMPNUM_FROM_HR      VARCHAR2(30 BYTE),
  EMPNUM_FROM_FILE    NUMBER,
  FULL_NAME           VARCHAR2(240 BYTE),
  FROM_FND            VARCHAR2(100 BYTE)        NOT NULL,
  USERNAME_FROM_FILE  VARCHAR2(200 BYTE),
  FROM_UMX            VARCHAR2(200 BYTE),
  ROLENAME_FROM_FILE  VARCHAR2(200 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
