DROP TABLE APPS.XX_FND_USER_MAINTENANCE CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_FND_USER_MAINTENANCE
(
  USER_NAME    VARCHAR2(200 BYTE),
  START_DATE   DATE,
  END_DATE     DATE,
  ENABLE_FLAG  VARCHAR2(10 BYTE),
  STATUS       VARCHAR2(50 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
