DROP TABLE APPS.XX_FND_NEW_USER CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_FND_NEW_USER
(
  EMPLOYEE_NUMBER  NUMBER,
  USER_NAME        VARCHAR2(200 BYTE),
  ROLE_NAME        VARCHAR2(200 BYTE),
  EXISTING_USER    VARCHAR2(1 BYTE),
  LINK_EMPLOYEE    VARCHAR2(1 BYTE),
  ROLE_KEY         VARCHAR2(200 BYTE),
  STATUS           VARCHAR2(25 BYTE),
  ATTRIBUTE1       VARCHAR2(100 BYTE),
  ATTRIBUTE2       VARCHAR2(100 BYTE),
  ATTRIBUTE3       VARCHAR2(100 BYTE),
  EMPLOYEE_ID      NUMBER
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
