DROP TABLE APPS.XX_FND_CONC_REQ_HOLD CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_FND_CONC_REQ_HOLD
(
  REQUEST_ID  NUMBER,
  HOLD_DATE   DATE,
  STATUS      VARCHAR2(100 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX APPS.XX_FND_CONC_REQ_HOLD_U1 ON APPS.XX_FND_CONC_REQ_HOLD
(REQUEST_ID)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
