DROP TABLE APPS.XX_GL_CONS_FLEXFIELD_MAP CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_GL_CONS_FLEXFIELD_MAP
(
  FLEXFIELD_MAP_ID        NUMBER,
  CONSOLIDATION_ID_11I    NUMBER,
  LAST_UPDATE_DATE        DATE,
  LAST_UPDATED_BY         NUMBER,
  TO_CODE_COMBINATION_ID  NUMBER,
  CREATION_DATE           DATE,
  CREATED_BY              NUMBER(15),
  LAST_UPDATE_LOGIN       NUMBER(15),
  SEGMENT1_LOW            VARCHAR2(25 BYTE),
  SEGMENT1_HIGH           VARCHAR2(25 BYTE),
  SEGMENT2_LOW            VARCHAR2(25 BYTE),
  SEGMENT2_HIGH           VARCHAR2(25 BYTE),
  SEGMENT3_LOW            VARCHAR2(25 BYTE),
  SEGMENT3_HIGH           VARCHAR2(25 BYTE),
  SEGMENT4_LOW            VARCHAR2(25 BYTE),
  SEGMENT4_HIGH           VARCHAR2(25 BYTE),
  SEGMENT5_LOW            VARCHAR2(25 BYTE),
  SEGMENT5_HIGH           VARCHAR2(25 BYTE),
  SEGMENT6_LOW            VARCHAR2(25 BYTE),
  SEGMENT6_HIGH           VARCHAR2(25 BYTE),
  SEGMENT7_LOW            VARCHAR2(25 BYTE),
  SEGMENT7_HIGH           VARCHAR2(25 BYTE),
  SEGMENT8_LOW            VARCHAR2(25 BYTE),
  SEGMENT8_HIGH           VARCHAR2(25 BYTE),
  SEGMENT9_LOW            VARCHAR2(25 BYTE),
  SEGMENT9_HIGH           VARCHAR2(25 BYTE),
  SEGMENT10_LOW           VARCHAR2(25 BYTE),
  SEGMENT10_HIGH          VARCHAR2(25 BYTE),
  SEGMENT11_LOW           VARCHAR2(25 BYTE),
  SEGMENT11_HIGH          VARCHAR2(25 BYTE),
  SEGMENT12_LOW           VARCHAR2(25 BYTE),
  SEGMENT12_HIGH          VARCHAR2(25 BYTE),
  SEGMENT13_LOW           VARCHAR2(25 BYTE),
  SEGMENT13_HIGH          VARCHAR2(25 BYTE),
  SEGMENT14_LOW           VARCHAR2(25 BYTE),
  SEGMENT14_HIGH          VARCHAR2(25 BYTE),
  SEGMENT15_LOW           VARCHAR2(25 BYTE),
  SEGMENT15_HIGH          VARCHAR2(25 BYTE),
  SEGMENT16_LOW           VARCHAR2(25 BYTE),
  SEGMENT16_HIGH          VARCHAR2(25 BYTE),
  SEGMENT17_LOW           VARCHAR2(25 BYTE),
  SEGMENT17_HIGH          VARCHAR2(25 BYTE),
  SEGMENT18_LOW           VARCHAR2(25 BYTE),
  SEGMENT18_HIGH          VARCHAR2(25 BYTE),
  SEGMENT19_LOW           VARCHAR2(25 BYTE),
  SEGMENT19_HIGH          VARCHAR2(25 BYTE),
  SEGMENT20_LOW           VARCHAR2(25 BYTE),
  SEGMENT20_HIGH          VARCHAR2(25 BYTE),
  SEGMENT21_LOW           VARCHAR2(25 BYTE),
  SEGMENT21_HIGH          VARCHAR2(25 BYTE),
  SEGMENT22_LOW           VARCHAR2(25 BYTE),
  SEGMENT22_HIGH          VARCHAR2(25 BYTE),
  SEGMENT23_LOW           VARCHAR2(25 BYTE),
  SEGMENT23_HIGH          VARCHAR2(25 BYTE),
  SEGMENT24_LOW           VARCHAR2(25 BYTE),
  SEGMENT24_HIGH          VARCHAR2(25 BYTE),
  SEGMENT25_LOW           VARCHAR2(25 BYTE),
  SEGMENT25_HIGH          VARCHAR2(25 BYTE),
  SEGMENT26_LOW           VARCHAR2(25 BYTE),
  SEGMENT26_HIGH          VARCHAR2(25 BYTE),
  SEGMENT27_LOW           VARCHAR2(25 BYTE),
  SEGMENT27_HIGH          VARCHAR2(25 BYTE),
  SEGMENT28_LOW           VARCHAR2(25 BYTE),
  SEGMENT28_HIGH          VARCHAR2(25 BYTE),
  SEGMENT29_LOW           VARCHAR2(25 BYTE),
  SEGMENT29_HIGH          VARCHAR2(25 BYTE),
  SEGMENT30_LOW           VARCHAR2(25 BYTE),
  SEGMENT30_HIGH          VARCHAR2(25 BYTE),
  ATTRIBUTE1              VARCHAR2(150 BYTE),
  ATTRIBUTE2              VARCHAR2(150 BYTE),
  ATTRIBUTE3              VARCHAR2(150 BYTE),
  ATTRIBUTE4              VARCHAR2(150 BYTE),
  ATTRIBUTE5              VARCHAR2(150 BYTE),
  CONTEXT                 VARCHAR2(150 BYTE),
  COA_MAPPING_ID          NUMBER(15),
  TO_SEGMENT1             VARCHAR2(30 BYTE),
  TO_SEGMENT2             VARCHAR2(30 BYTE),
  TO_SEGMENT3             VARCHAR2(30 BYTE),
  ERROR_MESSAGE           VARCHAR2(4000 BYTE),
  OVERLAPPING             VARCHAR2(100 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
