DROP TABLE APPS.XX_HR_TERM_EMP_HALOGEN_V CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_HR_TERM_EMP_HALOGEN_V
(
  USER_ID          NUMBER(15),
  USER_NAME        VARCHAR2(100 BYTE),
  EMAIL_ADDRESS    VARCHAR2(240 BYTE),
  FIRST_NAME       VARCHAR2(150 BYTE),
  LAST_NAME        VARCHAR2(150 BYTE)           NOT NULL,
  EMPLOYEE_NUMBER  VARCHAR2(30 BYTE),
  DEACTIVATE       CHAR(1 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


GRANT SELECT ON APPS.XX_HR_TERM_EMP_HALOGEN_V TO XXAPPSHRRO;
