DROP TABLE APPS.XX_IC_ASL_ITEMS CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_IC_ASL_ITEMS
(
  ITEM_ID                 NUMBER,
  VENDOR_ID               NUMBER,
  VENDOR_SITE_ID          NUMBER,
  USING_ORGANIZATION_ID   NUMBER,
  OWNING_ORGANIZATION_ID  NUMBER,
  PO_HEADER_ID            NUMBER,
  PO_LINE_ID              NUMBER,
  CONTRACT_PO_NUMBER      VARCHAR2(30 BYTE),
  VENDOR_NAME             VARCHAR2(400 BYTE),
  OPERATING_UNIT          VARCHAR2(30 BYTE),
  PRICE_LIST              VARCHAR2(400 BYTE),
  VENDOR_SITE_CODE        VARCHAR2(400 BYTE),
  ERROR_MESSAGE           VARCHAR2(4000 BYTE),
  ASL_ID                  NUMBER,
  ITEM                    VARCHAR2(40 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
