DROP TABLE APPS.XX_INV_EO_ANLYS_GBLTMP_TBL CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE APPS.XX_INV_EO_ANLYS_GBLTMP_TBL
(
  INVENTORY_ITEM_ID    NUMBER,
  ORGANIZATION_ID      NUMBER,
  ITEM_NUM             VARCHAR2(100 BYTE),
  ITEM_DESC            VARCHAR2(240 BYTE),
  ITEM_STATUS          VARCHAR2(100 BYTE),
  ITEM_LINE_CFICATION  VARCHAR2(100 BYTE),
  ITEM_TYPE            VARCHAR2(100 BYTE),
  ITEM_CREAT_DATE      DATE,
  FINANCIAL_CATEGORY   VARCHAR2(240 BYTE),
  UOM                  VARCHAR2(240 BYTE),
  LOT_CONTROL          VARCHAR2(240 BYTE),
  DIVISION             VARCHAR2(240 BYTE),
  BRAND                VARCHAR2(240 BYTE),
  PRODUCT_CLASS_VALUE  VARCHAR2(240 BYTE),
  PRODUCT_CLASS_DESC   VARCHAR2(240 BYTE),
  PRODUCT_TYPE_VALUE   VARCHAR2(240 BYTE),
  PRODUCT_TYPE_DESC    VARCHAR2(240 BYTE),
  INV_ORG_CODE         VARCHAR2(240 BYTE),
  ABC_CODE             VARCHAR2(240 BYTE),
  STANDARD_COST        NUMBER,
  ON_HAND_QTY          NUMBER,
  EXPIRING_LOT_QTY     NUMBER,
  QA_SUBINV_QTY        NUMBER,
  TRX_QTY_CUR          NUMBER,
  TRX_QTY_CUR_1        NUMBER,
  TRX_QTY_CUR_2        NUMBER,
  TRX_QTY_CUR_3        NUMBER,
  TRX_QTY_CUR_4        NUMBER,
  TRX_QTY_CUR_5        NUMBER,
  TRX_QTY_CUR_6        NUMBER,
  TRX_QTY_CUR_7        NUMBER,
  TRX_QTY_CUR_8        NUMBER,
  TRX_QTY_CUR_9        NUMBER,
  TRX_QTY_CUR_10       NUMBER,
  TRX_QTY_CUR_11       NUMBER,
  SALE_HQTY_CUR        NUMBER,
  SALE_HQTY_CUR_1      NUMBER,
  SALE_HQTY_CUR_2      NUMBER,
  SALE_HQTY_CUR_3      NUMBER,
  SALE_HQTY_CUR_4      NUMBER,
  SALE_HQTY_CUR_5      NUMBER,
  SALE_HQTY_CUR_6      NUMBER,
  SALE_HQTY_CUR_7      NUMBER,
  SALE_HQTY_CUR_8      NUMBER,
  SALE_HQTY_CUR_9      NUMBER,
  SALE_HQTY_CUR_10     NUMBER,
  SALE_HQTY_CUR_11     NUMBER,
  WIP_TRX_QTY_CUR      NUMBER,
  WIP_TRX_QTY_CUR_1    NUMBER,
  WIP_TRX_QTY_CUR_2    NUMBER,
  WIP_TRX_QTY_CUR_3    NUMBER,
  WIP_TRX_QTY_CUR_4    NUMBER,
  WIP_TRX_QTY_CUR_5    NUMBER,
  WIP_TRX_QTY_CUR_6    NUMBER,
  WIP_TRX_QTY_CUR_7    NUMBER,
  WIP_TRX_QTY_CUR_8    NUMBER,
  WIP_TRX_QTY_CUR_9    NUMBER,
  WIP_TRX_QTY_CUR_10   NUMBER,
  WIP_TRX_QTY_CUR_11   NUMBER
)
ON COMMIT PRESERVE ROWS
NOCACHE;


CREATE INDEX APPS.XX_INV_EO_ANLYS_GBLTMP_N1 ON APPS.XX_INV_EO_ANLYS_GBLTMP_TBL
(INVENTORY_ITEM_ID);

CREATE INDEX APPS.XX_INV_EO_ANLYS_GBLTMP_N2 ON APPS.XX_INV_EO_ANLYS_GBLTMP_TBL
(ORGANIZATION_ID);

CREATE INDEX APPS.XX_INV_EO_ANLYS_GBLTMP_N3 ON APPS.XX_INV_EO_ANLYS_GBLTMP_TBL
(INVENTORY_ITEM_ID, ORGANIZATION_ID);
