DROP TABLE APPS.XX_MTL_SYSTEM_ITEMS_ATTRIB29 CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_MTL_SYSTEM_ITEMS_ATTRIB29
(
  INVENTORY_ITEM_ID  NUMBER                     NOT NULL,
  SEGMENT1           VARCHAR2(40 BYTE),
  ORGANIZATION_ID    NUMBER                     NOT NULL,
  ATTRIBUTE29        VARCHAR2(240 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
