DROP TABLE APPS.XX_OM_ONETIME_SURGEON_DATA CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_OM_ONETIME_SURGEON_DATA
(
  ORDER_NUMBER      NUMBER,
  ORIG_SYS_DOC_REF  VARCHAR2(400 BYTE),
  ORDER_SOURCE      VARCHAR2(100 BYTE),
  SURGEON_NAME      VARCHAR2(400 BYTE),
  SURGEON_UPDATED   VARCHAR2(1 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
