DROP TABLE APPS.XX_PROFILE_EMAIL_STG CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_PROFILE_EMAIL_STG
(
  BATCH_ID          VARCHAR2(80 BYTE),
  PARTY_NUMBER      VARCHAR2(80 BYTE),
  PARTY_NAME        VARCHAR2(360 BYTE),
  ACCOUNT_NUMBER    VARCHAR2(60 BYTE),
  ATTRIBUTE2        VARCHAR2(150 BYTE),
  CUST_ACCOUNT_ID   NUMBER(15),
  LAST_UPDATED_BY   NUMBER,
  LAST_UPDATE_DATE  DATE,
  CREATION_DATE     DATE,
  CREATED_BY        NUMBER(15),
  REQUEST_ID        NUMBER(15),
  ERROR_CODE        NUMBER,
  ERROR_MESSAGE     VARCHAR2(240 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
