DROP TABLE APPS.XX_PROFILE_STG CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_PROFILE_STG
(
  BATCH_ID                  CHAR(33 BYTE),
  PARTY_NUMBER              VARCHAR2(30 BYTE),
  PARTY_NAME                VARCHAR2(360 BYTE),
  ACCOUNT_NUMBER            VARCHAR2(30 BYTE),
  CUST_ACCOUNT_ID           NUMBER(15),
  OVERALL_CREDIT_LIMIT      NUMBER,
  CURRENCY_CODE             VARCHAR2(15 BYTE),
  CUST_ACCOUNT_PROFILE_ID   NUMBER,
  CUST_ACCT_PROFILE_AMT_ID  NUMBER,
  AMOUNT_VERSION            NUMBER,
  CREATED_BY                NUMBER,
  CREATION_DATE             DATE,
  LAST_UPDATED_DATE         DATE,
  LAST_UPDATED_BY           NUMBER,
  STATUS                    CHAR(36 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
