DROP TABLE APPS.XX_PO_ASL_STG_BU_IRV CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_PO_ASL_STG_BU_IRV
(
  VENDOR_NAME     VARCHAR2(100 BYTE),
  VENDOR_ADDRESS  VARCHAR2(250 BYTE),
  ERROR_CNT       NUMBER
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
