DROP TABLE APPS.XX_PO_RULE_EXPENSE_ACCOUNTS CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_PO_RULE_EXPENSE_ACCOUNTS
(
  RULE_TYPE      VARCHAR2(30 BYTE),
  SEGMENT_NUM    VARCHAR2(100 BYTE),
  RULE_VALUE     VARCHAR2(50 BYTE),
  SEGMENT_VALUE  VARCHAR2(30 BYTE),
  RULE_VALUE_ID  NUMBER,
  ORG_ID         NUMBER
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
