DROP TABLE APPS.XX_RMIG_PROD_ROLE_LIST CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_RMIG_PROD_ROLE_LIST
(
  TRACK                VARCHAR2(50 BYTE),
  ROLE_NAME            VARCHAR2(100 BYTE),
  STATUS               VARCHAR2(100 BYTE),
  MODULE               VARCHAR2(50 BYTE),
  RESPONSIBILITY_NAME  VARCHAR2(200 BYTE),
  USER_MENU_NAME       VARCHAR2(150 BYTE),
  REQUEST_GROUP_NAME   VARCHAR2(100 BYTE),
  REQ_GRP_APPL         VARCHAR2(30 BYTE),
  ATTRIBUTE1           VARCHAR2(100 BYTE),
  ATTRIBUTE2           VARCHAR2(100 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


GRANT SELECT ON APPS.XX_RMIG_PROD_ROLE_LIST TO XXAPPSREAD;
