DROP TABLE APPS.XX_RMIG_USER_LOAD CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_RMIG_USER_LOAD
(
  EMPLOYEE     VARCHAR2(200 BYTE),
  USER_NAME    VARCHAR2(200 BYTE),
  DESCRIPTION  VARCHAR2(50 BYTE),
  EMPLOYEE_ID  NUMBER,
  STATUS       VARCHAR2(50 BYTE),
  ATTRIBUTE1   VARCHAR2(50 BYTE),
  ATTRIBUTE2   VARCHAR2(50 BYTE),
  ATTRIBUTE3   VARCHAR2(50 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
