DROP TABLE APPS.XX_SS_USER_REPS CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_SS_USER_REPS
(
  DIVISION     VARCHAR2(30 BYTE),
  REPID        NUMBER,
  SALESREP_ID  VARCHAR2(30 BYTE),
  NAME         VARCHAR2(400 BYTE),
  ACTIVE_FLAG  VARCHAR2(10 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON APPS.XX_SS_USER_REPS TO XXAPPSREAD;
