DROP TABLE APPS.XX_TEMP_CONCURRENT_PROGRAMS CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_TEMP_CONCURRENT_PROGRAMS
(
  APPLICATION_NAME         VARCHAR2(240 BYTE)   NOT NULL,
  USER_EXECUTABLE_NAME     VARCHAR2(240 BYTE)   NOT NULL,
  EXECUTABLE_NAME          VARCHAR2(30 BYTE)    NOT NULL,
  EXECUTION_FILE_NAME      VARCHAR2(61 BYTE),
  EXECUTABLE_TYPE          VARCHAR2(80 BYTE)    NOT NULL,
  CONCURRENT_PROGRAM_NAME  VARCHAR2(30 BYTE)    NOT NULL,
  DESCRIPTION              VARCHAR2(240 BYTE),
  ENABLED_FLAG             VARCHAR2(1 BYTE)     NOT NULL,
  CONCURRENT_PROGRAM_ID    NUMBER(15)           NOT NULL,
  APPLICATION_ID           NUMBER(15)           NOT NULL
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
