DROP TABLE APPS.XX_UPDATE_CUST_ATTRIBUTES_STG CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_UPDATE_CUST_ATTRIBUTES_STG
(
  RECORD_ID          NUMBER,
  ACCOUNT_NUMBER     VARCHAR2(30 BYTE),
  PARTY_SITE_NUMBER  VARCHAR2(100 BYTE),
  OPERATING_UNIT     VARCHAR2(240 BYTE),
  ATTRIBUTE1         VARCHAR2(250 BYTE),
  ATTRIBUTE2         VARCHAR2(250 BYTE),
  ATTRIBUTE3         VARCHAR2(250 BYTE),
  ATTRIBUTE4         VARCHAR2(250 BYTE),
  ATTRIBUTE5         VARCHAR2(250 BYTE),
  ATTRIBUTE6         VARCHAR2(250 BYTE),
  ATTRIBUTE7         VARCHAR2(250 BYTE),
  ATTRIBUTE8         VARCHAR2(250 BYTE),
  ATTRIBUTE9         VARCHAR2(250 BYTE),
  ATTRIBUTE10        VARCHAR2(250 BYTE),
  ATTRIBUTE11        VARCHAR2(250 BYTE),
  ATTRIBUTE12        VARCHAR2(250 BYTE),
  ATTRIBUTE13        VARCHAR2(250 BYTE),
  ATTRIBUTE14        VARCHAR2(250 BYTE),
  ATTRIBUTE15        VARCHAR2(250 BYTE),
  ATTRIBUTE16        VARCHAR2(250 BYTE),
  ATTRIBUTE17        VARCHAR2(250 BYTE),
  ATTRIBUTE18        VARCHAR2(250 BYTE),
  ATTRIBUTE19        VARCHAR2(250 BYTE),
  ATTRIBUTE20        VARCHAR2(250 BYTE),
  STATUS             VARCHAR2(1 BYTE),
  RECORD_STATUS      VARCHAR2(10 BYTE),
  ERROR_MESSAGE      VARCHAR2(2000 BYTE),
  CREATION_DATE      VARCHAR2(50 BYTE),
  CREATED_BY         NUMBER,
  LAST_UPDATE_DATE   VARCHAR2(50 BYTE),
  LAST_UPDATED_BY    NUMBER
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN APPS.XX_UPDATE_CUST_ATTRIBUTES_STG.ATTRIBUTE1 IS 'GPO_ENTITY';

COMMENT ON COLUMN APPS.XX_UPDATE_CUST_ATTRIBUTES_STG.ATTRIBUTE2 IS 'GLN_NUMBER';

COMMENT ON COLUMN APPS.XX_UPDATE_CUST_ATTRIBUTES_STG.ATTRIBUTE3 IS 'NATIONALITY';

COMMENT ON COLUMN APPS.XX_UPDATE_CUST_ATTRIBUTES_STG.ATTRIBUTE4 IS 'B2B_TRANSLATION';

COMMENT ON COLUMN APPS.XX_UPDATE_CUST_ATTRIBUTES_STG.ATTRIBUTE5 IS 'B2B_EDI_LOCATION';

COMMENT ON COLUMN APPS.XX_UPDATE_CUST_ATTRIBUTES_STG.ATTRIBUTE7 IS 'GHX_EDI_ENABLED';

COMMENT ON COLUMN APPS.XX_UPDATE_CUST_ATTRIBUTES_STG.ATTRIBUTE8 IS 'GHX_EDI_PAPER_INV';

COMMENT ON COLUMN APPS.XX_UPDATE_CUST_ATTRIBUTES_STG.ATTRIBUTE10 IS 'CERTIFICATE_OF_COMPLIANCE';

COMMENT ON COLUMN APPS.XX_UPDATE_CUST_ATTRIBUTES_STG.ATTRIBUTE17 IS 'REPORTING_GEO';

COMMENT ON COLUMN APPS.XX_UPDATE_CUST_ATTRIBUTES_STG.ATTRIBUTE18 IS 'IMS_ID';

COMMENT ON COLUMN APPS.XX_UPDATE_CUST_ATTRIBUTES_STG.ATTRIBUTE19 IS 'AGGREGATION_GROUP';

COMMENT ON COLUMN APPS.XX_UPDATE_CUST_ATTRIBUTES_STG.ATTRIBUTE20 IS 'IDN_HEALTH_SYSTEM';

COMMENT ON COLUMN APPS.XX_UPDATE_CUST_ATTRIBUTES_STG.STATUS IS 'Site Status';


GRANT SELECT ON APPS.XX_UPDATE_CUST_ATTRIBUTES_STG TO XXAPPSREAD;
