DROP TABLE APPS.XX_XTRX_HR_USR_ANALYSIS_T CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_XTRX_HR_USR_ANALYSIS_T
(
  LOGIN_HOUR         VARCHAR2(12 BYTE),
  TOTAL_LOGIN_COUNT  NUMBER,
  AVG_LOGIN_PER_HR   NUMBER,
  TOTAL_USAGE_MINS   NUMBER,
  AVG_MINS_USAGE     NUMBER,
  RESP_APPL_ID       NUMBER                     NOT NULL
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
