DROP TABLE APPS.XX_XRTX_ORG_STRUCTURE_T CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_XRTX_ORG_STRUCTURE_T
(
  ORG_LEVEL               VARCHAR2(50 BYTE),
  ORGANIZATION_ID         NUMBER(15),
  BUSINESS_GROUP_ID       NUMBER(15),
  OPERATING_UNIT          NUMBER(15),
  ORG_ID                  NUMBER(15),
  SITE_USE_CODE           VARCHAR2(30 BYTE),
  SHORT_CODE              VARCHAR2(150 BYTE),
  NAME                    VARCHAR2(240 BYTE),
  LEGAL_ENTITY_NAME       VARCHAR2(240 BYTE),
  PRIMARY_LEDGER_NAME     VARCHAR2(240 BYTE),
  BILL_TO_CNT             NUMBER(15),
  SHIP_TO_CNT             NUMBER(15),
  SUPPLIER_CNT            NUMBER(15),
  ACTIVE_ITEMS_CNT        NUMBER(15),
  ACTIVE_SUB_INVENTORIES  NUMBER(15),
  EMPLOYEE_CNT            NUMBER(15)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
