DROP TABLE APPS.XX_XRTX_TASK_T CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_XRTX_TASK_T
(
  ACTIVITY_ID           NUMBER,
  ACTIVITY_SEQ          NUMBER,
  ACTIVITY_NAME         VARCHAR2(200 BYTE),
  ACTIVITY_DESCRIPTION  VARCHAR2(4000 BYTE),
  CUSTOM_TYPE           VARCHAR2(100 BYTE),
  CUSTOM_OBJECT_ID      NUMBER,
  SUB_PROCESS_ID        NUMBER,
  ACTIVITY_CRITICALITY  NUMBER,
  ACTIVE_FLAG           VARCHAR2(1 BYTE)        DEFAULT 'Y'
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
