DROP TABLE APPS.XX_XRTX_MAS_CUS_WF_T CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_XRTX_MAS_CUS_WF_T
(
  ITEM_TYPE       VARCHAR2(8 BYTE)              NOT NULL,
  DISPLAY_NAME    VARCHAR2(80 BYTE)             NOT NULL,
  VERSION         NUMBER                        NOT NULL,
  ACTIVITY_COUNT  NUMBER,
  DESCRIPTION     VARCHAR2(240 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
