DROP TABLE APPS.XX_XRTX_CLASSIFICATION_T CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_XRTX_CLASSIFICATION_T
(
  SHORT_CODE             VARCHAR2(100 BYTE),
  APPLICATION            VARCHAR2(1000 BYTE),
  MODULE_CLASSIFICATION  VARCHAR2(100 BYTE),
  CLASSIFICATION_B       VARCHAR2(100 BYTE),
  CLASSIFICATION_C       VARCHAR2(100 BYTE),
  STATUS                 VARCHAR2(100 BYTE),
  APP_ID                 NUMBER,
  BASEPATH               VARCHAR2(20 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
