DROP TABLE APPS.XX_XRTX_MC_USER_COUNT_T CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_XRTX_MC_USER_COUNT_T
(
  MODULE_CLASSIFICATION    VARCHAR2(100 BYTE),
  TOTAL_MODULES_INSTALLED  NUMBER(30),
  USER_ACESS_MODULE_WISE   NUMBER(30)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
