DROP TABLE APPS.XX_XRTS_API_LIST_DETAILS CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_XRTS_API_LIST_DETAILS
(
  NAME_OF_CUSTOM_OBJECT_REF_API  VARCHAR2(400 BYTE),
  TYPE                           VARCHAR2(100 BYTE),
  CONCURRENT_PROGRAM_NAME        VARCHAR2(200 BYTE),
  API_NAME                       VARCHAR2(100 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
