DROP TABLE APPS.XX_XRTX_CUST_INT_ERR CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_XRTX_CUST_INT_ERR
(
  INTERFACE_STATUS  VARCHAR2(240 BYTE),
  CUSTOMER_NAME     VARCHAR2(360 BYTE)          NOT NULL,
  ORG_ID            NUMBER(15)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
