DROP TABLE APPS.XX_XRTX_PROCESS_T CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_XRTX_PROCESS_T
(
  PROCESS_ID           NUMBER,
  PROCESS_NAME         VARCHAR2(300 BYTE),
  PROCESS_DESCRIPTION  VARCHAR2(4000 BYTE),
  ACTIVE_FLAG          VARCHAR2(1 BYTE)         DEFAULT 'Y'
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
