DROP TABLE APPS.XX_XRTX_API_LIST CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_XRTX_API_LIST
(
  API_NAME                 VARCHAR2(200 BYTE),
  API_DESC                 VARCHAR2(400 BYTE),
  COUNT_OF_OBJECT_REF_API  NUMBER
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
