DROP TABLE APPS.XX_XRTX_CHILD_WF_T CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_XRTX_CHILD_WF_T
(
  ITEM_TYPE          VARCHAR2(8 BYTE)           NOT NULL,
  DISPLAY_NAME       VARCHAR2(80 BYTE)          NOT NULL,
  NAME               VARCHAR2(30 BYTE)          NOT NULL,
  VERSION            NUMBER                     NOT NULL,
  TYPE               VARCHAR2(8 BYTE)           NOT NULL,
  RERUN              VARCHAR2(8 BYTE)           NOT NULL,
  EXPAND_ROLE        VARCHAR2(1 BYTE)           NOT NULL,
  PROTECT_LEVEL      NUMBER                     NOT NULL,
  CUSTOM_LEVEL       NUMBER                     NOT NULL,
  BEGIN_DATE         DATE                       NOT NULL,
  END_DATE           DATE,
  FUNCTION           VARCHAR2(240 BYTE),
  RESULT_TYPE        VARCHAR2(30 BYTE),
  COST               NUMBER,
  READ_ROLE          VARCHAR2(320 BYTE),
  WRITE_ROLE         VARCHAR2(320 BYTE),
  EXECUTE_ROLE       VARCHAR2(320 BYTE),
  ICON_NAME          VARCHAR2(30 BYTE),
  MESSAGE            VARCHAR2(30 BYTE),
  ERROR_PROCESS      VARCHAR2(30 BYTE),
  ERROR_ITEM_TYPE    VARCHAR2(8 BYTE)           NOT NULL,
  RUNNABLE_FLAG      VARCHAR2(1 BYTE)           NOT NULL,
  FUNCTION_TYPE      VARCHAR2(30 BYTE),
  EVENT_NAME         VARCHAR2(240 BYTE),
  DIRECTION          VARCHAR2(30 BYTE),
  SECURITY_GROUP_ID  VARCHAR2(32 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
