DROP TABLE APPS.XX_XRTX_COSTOM_OAF_T CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_XRTX_COSTOM_OAF_T
(
  PERZ_DOC_ID    NUMBER(10),
  PERZ_DOC_PATH  VARCHAR2(4000 BYTE),
  OAF_PAGE       VARCHAR2(4000 BYTE),
  MODULE         VARCHAR2(4000 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
