DROP TABLE APPS.XX_XRTX_ITEMTYPE_INV_T CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_XRTX_ITEMTYPE_INV_T
(
  ITEM_CNT           NUMBER,
  ITEM_TYPE          VARCHAR2(30 BYTE),
  ORGANIZATION_CODE  VARCHAR2(3 BYTE),
  ORGANIZATION_ID    NUMBER                     NOT NULL,
  MEANING            VARCHAR2(80 BYTE)          NOT NULL
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
