DROP TABLE APPS.XX_XRTX_MODULE_NAME_T CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_XRTX_MODULE_NAME_T
(
  APPLICATION_SHORT_NAME  VARCHAR2(50 BYTE)     NOT NULL,
  APPLICATION_ID          NUMBER                NOT NULL,
  APPLICATION_NAME        VARCHAR2(240 BYTE)    NOT NULL,
  ID_FLEX_NAME            VARCHAR2(30 BYTE)     NOT NULL,
  ID_FLEX_CODE            VARCHAR2(4 BYTE)      NOT NULL
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
