DROP TABLE APPS.XX_XRTX_SUB_PROCESS_T CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_XRTX_SUB_PROCESS_T
(
  SUB_PROCESS_ID           NUMBER,
  SUB_PROCESS_SEQ          NUMBER,
  SUB_PROCESS_NAME         VARCHAR2(200 BYTE),
  SUB_PROCESS_DESCRIPTION  VARCHAR2(4000 BYTE),
  BUSINESS_USAGE           VARCHAR2(100 BYTE),
  P1_TICKET                NUMBER,
  P2_TICKET                NUMBER,
  P3_TICKET                NUMBER,
  PROCESS_ID               NUMBER,
  ACTIVE_FLAG              VARCHAR2(1 BYTE)     DEFAULT 'Y'
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
