DROP TABLE APPS.XX_XRTX_CUST_ERROR_CODES CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_XRTX_CUST_ERROR_CODES
(
  ERROR_CODE     VARCHAR2(30 BYTE),
  ERROR_MEANING  VARCHAR2(300 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
