DROP TABLE APPS.XX_XRTX_MAS_FORPER_T CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_XRTX_MAS_FORPER_T
(
  FUNCTION_NAME   VARCHAR2(480 BYTE)            NOT NULL,
  FORM_NAME       VARCHAR2(30 BYTE)             NOT NULL,
  USER_FORM_NAME  VARCHAR2(80 BYTE)             NOT NULL,
  FORM_ID         NUMBER                        NOT NULL
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
