DROP TABLE APPS.XX_XRTX_MASTER_ITEM_T CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_XRTX_MASTER_ITEM_T
(
  MASTER_ORGANIZATION_ID  NUMBER,
  MASTER_ORG_CODE         VARCHAR2(3 BYTE),
  MASTER_ORG_NAME         VARCHAR2(240 BYTE),
  BUSINESS_GROUP_ID       NUMBER(15),
  INV_ORGS_COUNT          NUMBER,
  NO_OF_ITEMS             NUMBER,
  ITEMS_MANUAL_CREATE     NUMBER,
  ITEM_INTERFACE_CREATE   NUMBER
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
