DROP TABLE APPS.XXCUST_UPLOADDATA_FROMFILE_TAB CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE APPS.XXCUST_UPLOADDATA_FROMFILE_TAB
(
  RECORD_ID          NUMBER,
  XLS_NAME           VARCHAR2(100 BYTE),
  XLS_BLOB           BLOB,
  FIELD_SEP          VARCHAR2(1 BYTE),
  DATE_FORMAT        VARCHAR2(30 BYTE),
  OPERATION_FLAG     VARCHAR2(1 BYTE),
  UPLOAD_CRITERIA    VARCHAR2(1 BYTE),
  CREATION_DATE      DATE,
  CREATED_BY         NUMBER,
  LAST_UPDATED_BY    NUMBER,
  LAST_UPDATE_DATE   DATE,
  LAST_UPDATE_LOGIN  NUMBER
)
ON COMMIT PRESERVE ROWS
NOCACHE;


GRANT SELECT ON APPS.XXCUST_UPLOADDATA_FROMFILE_TAB TO INTG_XX_NONHR_RO;
