DROP TABLE APPS.XXINTG_APPLICANT_MAYLIVE_TAB CASCADE CONSTRAINTS;

CREATE TABLE APPS.XXINTG_APPLICANT_MAYLIVE_TAB
(
  PERSON_ID         NUMBER,
  APPLICANT_NUMBER  VARCHAR2(100 BYTE),
  FULL_NAME         VARCHAR2(200 BYTE),
  USER_PERSON_TYPE  VARCHAR2(100 BYTE),
  UNIQUE_ID         VARCHAR2(100 BYTE),
  USER_NAME_EMAIL   VARCHAR2(100 BYTE),
  STATUS            VARCHAR2(40 BYTE),
  ERROR_MESSAGE     VARCHAR2(400 BYTE),
  EXTRA_ATTRIBUTE1  VARCHAR2(200 BYTE),
  EXTRA_ATTRIBUTE2  VARCHAR2(200 BYTE),
  EXTRA_ATTRIBUTE3  VARCHAR2(200 BYTE),
  EXTRA_ATTRIBUTE4  VARCHAR2(200 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
