DROP TABLE APPS.XXINTG_REG CASCADE CONSTRAINTS;

CREATE TABLE APPS.XXINTG_REG
(
  COUNTRY_CODE          VARCHAR2(100 BYTE),
  COUNTRY_REGION_CODE   VARCHAR2(100 BYTE),
  STATE_CODE            VARCHAR2(100 BYTE),
  CITY_CODE             VARCHAR2(100 BYTE),
  PORT_FLAG             VARCHAR2(10 BYTE),
  AIRPORT_FLAG          VARCHAR2(10 BYTE),
  ROAD_TERMINAL_FLAG    VARCHAR2(10 BYTE),
  RAIL_TERMINAL_FLAG    VARCHAR2(10 BYTE),
  LONGITUDE             NUMBER,
  LATITUDE              NUMBER,
  TIMEZONE              VARCHAR2(30 BYTE),
  CONTINENT             VARCHAR2(600 BYTE),
  COUNTRY               VARCHAR2(800 BYTE),
  COUNTRY_REGION        VARCHAR2(600 BYTE),
  STATE                 VARCHAR2(600 BYTE),
  CITY                  VARCHAR2(600 BYTE),
  ALTERNATE_NAME        VARCHAR2(600 BYTE),
  COUNTY                VARCHAR2(600 BYTE),
  POSTAL_CODE_FROM      VARCHAR2(600 BYTE),
  POSTAL_CODE_TO        VARCHAR2(600 BYTE),
  REGION_ID             NUMBER,
  PARENT_REGION_ID      NUMBER,
  DECONSOL_LOCATION_ID  NUMBER,
  ZONE_LEVEL            NUMBER,
  ZONE                  VARCHAR2(600 BYTE),
  STATUS                VARCHAR2(5 BYTE),
  NEW_REGION            NUMBER,
  ERROR_DESC            VARCHAR2(2000 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
