DROP TABLE APPS.XXINTG_HR_ORGS CASCADE CONSTRAINTS;

CREATE TABLE APPS.XXINTG_HR_ORGS
(
  ORGANIZATION_ID        NUMBER(10),
  SEGMENT1               VARCHAR2(10 BYTE),
  SEGMENT2               VARCHAR2(10 BYTE),
  SEGMENT3               VARCHAR2(10 BYTE),
  SEGMENT4               VARCHAR2(10 BYTE),
  SEGMENT5               VARCHAR2(10 BYTE),
  SEGMENT6               VARCHAR2(10 BYTE),
  SEGMENT7               VARCHAR2(10 BYTE),
  SEGMENT8               VARCHAR2(10 BYTE),
  OBJECT_VERSION_NUMBER  NUMBER(10)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
