DROP TABLE APPS.XXINTG_MIG_SCRIPT_DOWNLOAD CASCADE CONSTRAINTS;

CREATE TABLE APPS.XXINTG_MIG_SCRIPT_DOWNLOAD
(
  DOWNLOAD_SCRIPT  VARCHAR2(4000 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
