DROP TABLE APPS.XXQPPRCINC_ITEM_DATA CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE APPS.XXQPPRCINC_ITEM_DATA
(
  QUANTITY_ORDERED    NUMBER,
  UNIT_SELLING_PRICE  NUMBER,
  INVENTORY_ITEM_ID   NUMBER
)
ON COMMIT PRESERVE ROWS
NOCACHE;


CREATE INDEX APPS.XXQPPRC_INDEX_ITEM_DATA ON APPS.XXQPPRCINC_ITEM_DATA
(INVENTORY_ITEM_ID);
