DROP TABLE APPS.XXSS_INTG_UNSPC_CODE_BKP CASCADE CONSTRAINTS;

CREATE TABLE APPS.XXSS_INTG_UNSPC_CODE_BKP
(
  ROW_ID                      ROWID,
  FLEX_VALUE_SET_ID           NUMBER(10)        NOT NULL,
  FLEX_VALUE_ID               NUMBER(15)        NOT NULL,
  FLEX_VALUE                  VARCHAR2(150 BYTE) NOT NULL,
  LAST_UPDATE_DATE            DATE              NOT NULL,
  LAST_UPDATED_BY             NUMBER(15)        NOT NULL,
  CREATION_DATE               DATE              NOT NULL,
  CREATED_BY                  NUMBER(15)        NOT NULL,
  LAST_UPDATE_LOGIN           NUMBER(15),
  ENABLED_FLAG                VARCHAR2(1 BYTE)  NOT NULL,
  SUMMARY_FLAG                VARCHAR2(1 BYTE)  NOT NULL,
  START_DATE_ACTIVE           DATE,
  END_DATE_ACTIVE             DATE,
  PARENT_FLEX_VALUE_LOW       VARCHAR2(60 BYTE),
  PARENT_FLEX_VALUE_HIGH      VARCHAR2(60 BYTE),
  STRUCTURED_HIERARCHY_LEVEL  NUMBER(15),
  HIERARCHY_LEVEL             VARCHAR2(30 BYTE),
  COMPILED_VALUE_ATTRIBUTES   VARCHAR2(2000 BYTE),
  VALUE_CATEGORY              VARCHAR2(30 BYTE),
  ATTRIBUTE1                  VARCHAR2(240 BYTE),
  ATTRIBUTE2                  VARCHAR2(240 BYTE),
  ATTRIBUTE3                  VARCHAR2(240 BYTE),
  ATTRIBUTE4                  VARCHAR2(240 BYTE),
  ATTRIBUTE5                  VARCHAR2(240 BYTE),
  ATTRIBUTE6                  VARCHAR2(240 BYTE),
  ATTRIBUTE7                  VARCHAR2(240 BYTE),
  ATTRIBUTE8                  VARCHAR2(240 BYTE),
  ATTRIBUTE9                  VARCHAR2(240 BYTE),
  ATTRIBUTE10                 VARCHAR2(240 BYTE),
  ATTRIBUTE11                 VARCHAR2(240 BYTE),
  ATTRIBUTE12                 VARCHAR2(240 BYTE),
  ATTRIBUTE13                 VARCHAR2(240 BYTE),
  ATTRIBUTE14                 VARCHAR2(240 BYTE),
  ATTRIBUTE15                 VARCHAR2(240 BYTE),
  ATTRIBUTE16                 VARCHAR2(240 BYTE),
  ATTRIBUTE17                 VARCHAR2(240 BYTE),
  ATTRIBUTE18                 VARCHAR2(240 BYTE),
  ATTRIBUTE19                 VARCHAR2(240 BYTE),
  ATTRIBUTE20                 VARCHAR2(240 BYTE),
  ATTRIBUTE21                 VARCHAR2(240 BYTE),
  ATTRIBUTE22                 VARCHAR2(240 BYTE),
  ATTRIBUTE23                 VARCHAR2(240 BYTE),
  ATTRIBUTE24                 VARCHAR2(240 BYTE),
  ATTRIBUTE25                 VARCHAR2(240 BYTE),
  ATTRIBUTE26                 VARCHAR2(240 BYTE),
  ATTRIBUTE27                 VARCHAR2(240 BYTE),
  ATTRIBUTE28                 VARCHAR2(240 BYTE),
  ATTRIBUTE29                 VARCHAR2(240 BYTE),
  ATTRIBUTE30                 VARCHAR2(240 BYTE),
  ATTRIBUTE31                 VARCHAR2(240 BYTE),
  ATTRIBUTE32                 VARCHAR2(240 BYTE),
  ATTRIBUTE33                 VARCHAR2(240 BYTE),
  ATTRIBUTE34                 VARCHAR2(240 BYTE),
  ATTRIBUTE35                 VARCHAR2(240 BYTE),
  ATTRIBUTE36                 VARCHAR2(240 BYTE),
  ATTRIBUTE37                 VARCHAR2(240 BYTE),
  ATTRIBUTE38                 VARCHAR2(240 BYTE),
  ATTRIBUTE39                 VARCHAR2(240 BYTE),
  ATTRIBUTE40                 VARCHAR2(240 BYTE),
  ATTRIBUTE41                 VARCHAR2(240 BYTE),
  ATTRIBUTE42                 VARCHAR2(240 BYTE),
  ATTRIBUTE43                 VARCHAR2(240 BYTE),
  ATTRIBUTE44                 VARCHAR2(240 BYTE),
  ATTRIBUTE45                 VARCHAR2(240 BYTE),
  ATTRIBUTE46                 VARCHAR2(240 BYTE),
  ATTRIBUTE47                 VARCHAR2(240 BYTE),
  ATTRIBUTE48                 VARCHAR2(240 BYTE),
  ATTRIBUTE49                 VARCHAR2(240 BYTE),
  ATTRIBUTE50                 VARCHAR2(240 BYTE),
  FLEX_VALUE_MEANING          VARCHAR2(150 BYTE) NOT NULL,
  DESCRIPTION                 VARCHAR2(240 BYTE),
  ATTRIBUTE_SORT_ORDER        NUMBER(15)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
