DROP TABLE APPS.XXSS_HR_EMP_CENSUS_STG CASCADE CONSTRAINTS;

CREATE TABLE APPS.XXSS_HR_EMP_CENSUS_STG
(
  PERSON_ID                 NUMBER(30),
  NATIONAL_IDENTIFIER       VARCHAR2(30 BYTE),
  EMPLOYEE_NUMBER           VARCHAR2(80 BYTE),
  LAST_NAME                 VARCHAR2(200 BYTE),
  FIRST_NAME                VARCHAR2(200 BYTE),
  MIDDLE_NAME               VARCHAR2(200 BYTE),
  GENDER                    VARCHAR2(20 BYTE),
  MARITAL_STATUS            VARCHAR2(100 BYTE),
  DATE_OF_BIRTH             VARCHAR2(50 BYTE),
  HIRE_DATE                 VARCHAR2(50 BYTE),
  ADJUSTED_HIRE_DATE        VARCHAR2(50 BYTE),
  ADDRESS_LINE1             VARCHAR2(200 BYTE),
  ADDRESS_LINE2             VARCHAR2(200 BYTE),
  CITY                      VARCHAR2(200 BYTE),
  STATE                     VARCHAR2(50 BYTE),
  ZIP_CODE                  VARCHAR2(50 BYTE),
  WORK_PHONE                VARCHAR2(50 BYTE),
  HOME_PHONE                VARCHAR2(50 BYTE),
  WORK_LOCATION             VARCHAR2(100 BYTE),
  EMAIL_ADDRESS             VARCHAR2(200 BYTE),
  GRE                       VARCHAR2(200 BYTE),
  HR_ORGANIZATIONS          VARCHAR2(200 BYTE),
  ASSIGNMENT_CHANGE_REASON  VARCHAR2(200 BYTE),
  POSITION                  VARCHAR2(200 BYTE),
  PAYROLL_NAME              VARCHAR2(200 BYTE),
  ASSIGNMENT_STATUS         VARCHAR2(200 BYTE),
  FLSA_CODE                 VARCHAR2(200 BYTE),
  ASSIGNMENT_CATEGORY       VARCHAR2(200 BYTE),
  WORKING_HOURS             VARCHAR2(50 BYTE),
  SALARY_BASIS              VARCHAR2(200 BYTE),
  BASE_SALARY               VARCHAR2(50 BYTE),
  ACTUAL_TERMINATION_DATE   VARCHAR2(50 BYTE),
  LEAVING_REASON            VARCHAR2(200 BYTE),
  CREATION_DATE             DATE,
  STATUS                    VARCHAR2(10 BYTE),
  ERROR_MESSAGE             VARCHAR2(2000 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX APPS.XXSS_HR_EMP_CENSUS_IND ON APPS.XXSS_HR_EMP_CENSUS_STG
(PERSON_ID)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
