DROP TABLE APPS.XXTINTG_BR100 CASCADE CONSTRAINTS;

CREATE TABLE APPS.XXTINTG_BR100
(
  COUNTRY           VARCHAR2(800 BYTE),
  COUNTRY_CODE      VARCHAR2(100 BYTE),
  STATE             VARCHAR2(600 BYTE),
  CITY              VARCHAR2(600 BYTE),
  POSTAL_CODE_FROM  VARCHAR2(600 BYTE),
  POSTAL_CODE_TO    VARCHAR2(600 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
