ALTER TABLE APPS.XXINTG_MIG_SCRIPT_MENU
  DROP CONSTRAINT XXINTG_MIG_SCRIPT_MENU_U1;

ALTER TABLE APPS.XXINTG_MIG_SCRIPT_MENU ADD (
  CONSTRAINT XXINTG_MIG_SCRIPT_MENU_U1
  UNIQUE (RESP_CODE, MENU_CODE)
  ENABLE VALIDATE);
