ALTER TABLE APPS.XXINTG_MIG_SCRIPT_RESP
  DROP CONSTRAINT XXINTG_MIG_SCRIPT_RESP_U1;

ALTER TABLE APPS.XXINTG_MIG_SCRIPT_RESP ADD (
  CONSTRAINT XXINTG_MIG_SCRIPT_RESP_U1
  UNIQUE (ROLE_CODE, RESP_CODE)
  ENABLE VALIDATE);
