DROP VIEW APPS.FEM_INTG_BAL_RULE_BSVS_V;

/* Formatted on 6/6/2016 5:00:36 PM (QP5 v5.277) */
CREATE OR REPLACE FORCE VIEW APPS.FEM_INTG_BAL_RULE_BSVS_V
(
   FLEX_VALUE,
   DESCRIPTION
)
AS
   SELECT '' flex_value, '' description
     FROM DUAL
    WHERE 0 = 1;


CREATE OR REPLACE SYNONYM ETLEBSUSER.FEM_INTG_BAL_RULE_BSVS_V FOR APPS.FEM_INTG_BAL_RULE_BSVS_V;


GRANT SELECT ON APPS.FEM_INTG_BAL_RULE_BSVS_V TO INTG_NONHR_NONXX_RO;

GRANT SELECT ON APPS.FEM_INTG_BAL_RULE_BSVS_V TO SS_ETL_RO;
