DROP VIEW APPS.XX_XRTX_OU_V;

/* Formatted on 6/6/2016 4:56:32 PM (QP5 v5.277) */
CREATE OR REPLACE FORCE VIEW APPS.XX_XRTX_OU_V
(
   "Short Code",
   "Description"
)
AS
   SELECT HOU.SHORT_CODE "Short Code", NAME "Description"
     FROM HR_OPERATING_UNITS HOU, GMF_LEGAL_ENTITIES GLE
    WHERE DEFAULT_LEGAL_CONTEXT_ID = LEGAL_ENTITY_ID;
