DROP VIEW APPS.XX_XRTX_LEGAL_ENTITIES_V;

/* Formatted on 6/6/2016 4:56:39 PM (QP5 v5.277) */
CREATE OR REPLACE FORCE VIEW APPS.XX_XRTX_LEGAL_ENTITIES_V
(
   LEGALENTITIES
)
AS
   SELECT COUNT (NAME) AS legalentities FROM XLE_ENTITY_PROFILES;
